### ISSUE TITLE
当新增用户名重复的用户时，返回的文案不太合理

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#11]
![image](https://user-images.githubusercontent.com/23573286/38171101-3de5cc6c-35c5-11e8-8d48-a55790d331b9.png)
建议可改成“该用户已存在”

**Comment by ConnieZheng** [comment]
后端返回的status需要增加一个duplicateUserNameFail @YukiZou

**Comment by YukiZou** [comment]
已解决 @zcx012 
![image](https://user-images.githubusercontent.com/34700003/38285957-5bb30d18-37f5-11e8-8dbc-5c2d36dbc6f1.png)

**Comment by zcx012** [comment]
Ack
