### ISSUE TITLE
用户数较多时，界面展示控件重合

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#13]
![image](https://user-images.githubusercontent.com/23573286/38172277-031880c2-35dc-11e8-997f-ca988222dc60.png)

**Comment by ConnieZheng** [comment]
目前改成了如下图的样子，虽然不是最好的解决方法，但是你先看看能否接受这样的界面

![default](https://user-images.githubusercontent.com/22384101/38186708-d36a8036-3686-11e8-8994-19edddf9d00e.png)

另外，分页旁的”搜索用户“按钮被我去除了，用来保证PC端的分页能显示。搜索框按Enter键来进行搜索。

**Comment by zcx012** [comment]
Ack
