### ISSUE TITLE
管理员用户新增用户类型为超级管理员的用户时，提示建议修改，或者不允许其新增该类型用户

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#14]
![image](https://user-images.githubusercontent.com/23573286/38224202-8c172054-3721-11e8-88f3-7330af67f0ce.png)

**Comment by zcx012** [comment]
![image](https://user-images.githubusercontent.com/23573286/38224242-c0c6ef32-3721-11e8-8ec6-56ab151f8fcb.png)
同理，新增管理员用户

**Comment by YukiZou** [comment]
管理员用户好像只能新增普通用户，界面是这样的
![image](https://user-images.githubusercontent.com/34700003/38226146-aa33e1ea-372a-11e8-9df3-ec21d344bddd.png)
@zcx012

**Comment by zcx012** [comment]
Ack
