### ISSUE TITLE
Edge浏览器适配出现问题，页头标题消失

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#15]
![image](https://user-images.githubusercontent.com/23573286/38419490-45a2bbc4-39d3-11e8-8205-2560f6eadc94.png)

**Comment by ConnieZheng** [comment]
这个是我为小屏幕PC做的适配，当整个页面的宽度小于等于992px时，标题栏的文字部分会被隐藏。
不是bug，可以在chrome上F12将页面宽度设置恰为992px体验一下（本来想放图片的，总上传不了）

**Comment by zcx012** [comment]
Ack
