### ISSUE TITLE
用户修改头像，不支持中文名称的图片

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#16]
![image](https://user-images.githubusercontent.com/23573286/38422018-d607934e-39db-11e8-9fcc-ff2308c205c4.png)

**Comment by zcx012** [comment]
ack

**Comment by ConnieZheng** [comment]
fixed, pls check, 修改tomcat配置

> tomcat/bin/catalina.sh
`
export LANG=zh_CN.UTF-8
`

**Comment by zcx012** [comment]
ack
