### ISSUE TITLE
当题干较长时，题干内容全部显示，影响了浏览效果，建议题干超过一定字数后替换为省略号

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#19]
![image](https://user-images.githubusercontent.com/23573286/38422383-1cd8e682-39dd-11e8-8a2d-e29b0e25428c.png)

**Comment by ConnieZheng** [comment]
试题的题干和流程的步骤详情都做了超过40字显示省略号的功能
![image](https://user-images.githubusercontent.com/22384101/38479427-a4c8411c-3bf1-11e8-8f9f-cb93f757d4f2.png)
![image](https://user-images.githubusercontent.com/22384101/38479446-cc30aca8-3bf1-11e8-8e40-1189d86a56a6.png)

**Comment by zcx012** [comment]
ack
