### ISSUE TITLE
试题界面显示问题，具体描述及复现路径如下

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#22]
1、先点击某个试题的修改试题按钮后取消
2、再点击另一个试题的修改试题按钮后取消
3、发现第二个被点击的试题，其题干内容显示为了第一个试题的内容

![image](https://user-images.githubusercontent.com/23573286/38451476-1601e5bc-3a63-11e8-8070-b307e030617d.png)
![image](https://user-images.githubusercontent.com/23573286/38451501-90d6ce7e-3a63-11e8-9032-4b91491eb718.png)

**Comment by ConnieZheng** [comment]
fixed, pls check

**Comment by zcx012** [comment]
ack
