### ISSUE TITLE
按照试题编号搜索框，输入非数字编号时，如字母，搜索结果显示所有题目，建议显示“无搜索结果”或限制只可以输入数字

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#24]
![image](https://user-images.githubusercontent.com/23573286/38451585-1d986c90-3a65-11e8-9f0c-7d3ca818343e.png)

**Comment by ConnieZheng** [comment]
fixed, pls check

**Comment by zcx012** [comment]
当前设置为不可输入除数字外其它字符
