### ISSUE TITLE
从其它模块管理页点击左侧首页返回首页时，上方的页头仍然显示在之前的模块上，且此时上方的首页按钮无法点击

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#25]
![image](https://user-images.githubusercontent.com/23573286/38451594-7ecf3778-3a65-11e8-93ab-716249beb8d0.png)
![image](https://user-images.githubusercontent.com/23573286/38451616-ee6f78ea-3a65-11e8-93c9-e21427578d03.png)

**Comment by ConnieZheng** [comment]
fixed, pls check

**Comment by zcx012** [comment]
ack
