### ISSUE TITLE
科室管理界面显示问题，具体描述及复现路径如下

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#26]
复现描述：（同之前的试题管理出现的bug）
1、先点击某个科室的修改科室按钮后取消
2、再点击另一个科室的修改科室按钮后取消
3、发现第二个被点击的科室，其内容显示为了第一个科室的内容

**Comment by ConnieZheng** [comment]
fiexd, pls check

**Comment by zcx012** [comment]
ack
