### ISSUE TITLE
流程管理 在新增某一流程时，没有显示下一步操作，无法添加图片和视频

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#29]
![image](https://user-images.githubusercontent.com/23573286/38650840-a6e71158-3e30-11e8-9788-6b4b2ad216e4.png)

**Comment by ConnieZheng** [comment]
目前偷懒，只做了提示信息：
![image](https://user-images.githubusercontent.com/22384101/38662685-b24e05e2-3e67-11e8-9805-a7aea0dd187d.png)

**Comment by zcx012** [comment]
ack
