### ISSUE TITLE
流程管理，在修改详情页面，显示基本信息时，上方导航栏对应的是图片信息。同理，显示图片信息时，导航栏显示的是视频信息

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#30]
![image](https://user-images.githubusercontent.com/23573286/38650956-41f8166a-3e31-11e8-98f2-493577af3dfe.png)

**Comment by ConnieZheng** [comment]
fixed

**Comment by zcx012** [comment]
ack
