### ISSUE TITLE
登录页 ，查看和隐藏密码功能当先点击了页面其它处后，再回来点击失效

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#6]
![image](https://user-images.githubusercontent.com/23573286/38170291-3fee149e-35b4-11e8-92c9-3306b94bedb3.png)

![image](https://user-images.githubusercontent.com/23573286/38170285-0e1fa202-35b4-11e8-9d02-388fb1caa617.png)

@ConnieZheng

**Comment by ConnieZheng** [comment]
*测试后发现，密码框右侧的小眼睛功能只有IE和edge上有，怀疑是Windows的功能*
 
现已添加CSS样式，修复该问题
 [参考代码](http://www.cnblogs.com/ilovewindy/p/3820179.html)

@zcx012

**Comment by zcx012** [comment]
Ack
