### ISSUE TITLE
新增用户的弹出框在出现红色提示并关掉后，再次打开，红色提示依然存在

### ISSUE THREAD

**Issue by zcx012** [YukiZou/pet-hospital#7]
![image](https://user-images.githubusercontent.com/23573286/38170399-640908fe-35b7-11e8-9a64-38a6d75f2988.png)

**Comment by zcx012** [comment]
@ConnieZheng

**Comment by ConnieZheng** [comment]
未resetFields
解决方法：捕获close事件，resetfields
已修复 @zcx012

**Comment by zcx012** [comment]
Ack
